M=10
R=7
L=19
B=15

sum=M+R+L+B
print("THE SUM IS ",sum)

AVERAGE=sum/4
print("THE AVERAGE IS ", AVERAGE)

#CALCULATING THE NOTES OF ANY PARTICULAR AMOUNT
AMOUNT=int(input("ENTER THE TOTAL AMOUNT: "))
NOTE1=AMOUNT//100
NOTE2=(AMOUNT%100)//50
NOTE3=((AMOUNT%100)%50)//10

print("THE NOTE OF 100", NOTE1)
print("THE NOTE OF 50", NOTE2)
print("THE NOTE OF 10", NOTE3)

#CALCULATING THE PERCENTAGE OF TOTAL MARKS 
MATHS=int(input("MATHS: "))
ENGLISH=int(input("ENGLISH: "))
SCIENCE=int(input("SCIENCE: "))
SS=int(input("SS: "))

sum=MATHS+ENGLISH+SCIENCE+SS
print("THE SUM IS ",sum)

PERCENTAGE=(sum/400)*100
print("YHE PERCENTAGE IS " , PERCENTAGE)